apiVersion: v1
kind: Namespace
metadata:
  name: auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: auth
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.1
          args: ["start-dev", "--import-realm"]
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_HTTP_PORT
              value: "8080"
            - name: KC_PROXY_HEADERS
              value: "xforwarded"
            - name: KC_LOG_LEVEL
              value: "INFO"
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: realm-config-volume
              mountPath: /opt/keycloak/data/import/dev-realm.json
              subPath: dev-realm.json
          resources:
            limits:
              memory: "768Mi"
              cpu: "1000m"
            requests:
              memory: "512Mi"
              cpu: "250m"
      volumes:
        - name: realm-config-volume
          configMap:
            name: keycloak-realm-import
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: auth
spec:
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP